"use strict";
var __cov_p_$t2LNtAVB24eAC0nJR3A = (Function('return this'))();
if (!__cov_p_$t2LNtAVB24eAC0nJR3A.__coverage__) { __cov_p_$t2LNtAVB24eAC0nJR3A.__coverage__ = {}; }
__cov_p_$t2LNtAVB24eAC0nJR3A = __cov_p_$t2LNtAVB24eAC0nJR3A.__coverage__;
if (!(__cov_p_$t2LNtAVB24eAC0nJR3A['c:\\Users\\vnaraujo\\projects\\stryker-mocha-chai-poc\\src\\module.js'])) {
   __cov_p_$t2LNtAVB24eAC0nJR3A['c:\\Users\\vnaraujo\\projects\\stryker-mocha-chai-poc\\src\\module.js'] = {"path":"c:\\Users\\vnaraujo\\projects\\stryker-mocha-chai-poc\\src\\module.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0},"b":{"1":[0,0]},"f":{},"fnMap":{},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":5,"column":2}},"2":{"start":{"line":4,"column":4},"end":{"line":4,"column":23}},"3":{"start":{"line":7,"column":0},"end":{"line":9,"column":2}},"4":{"start":{"line":8,"column":4},"end":{"line":8,"column":20}},"5":{"start":{"line":11,"column":0},"end":{"line":13,"column":2}},"6":{"start":{"line":12,"column":4},"end":{"line":12,"column":20}},"7":{"start":{"line":15,"column":0},"end":{"line":17,"column":2}},"8":{"start":{"line":16,"column":4},"end":{"line":16,"column":62}},"9":{"start":{"line":19,"column":0},"end":{"line":24,"column":2}},"10":{"start":{"line":26,"column":0},"end":{"line":26,"column":26}}},"branchMap":{"1":{"line":16,"type":"cond-expr","locations":[{"start":{"line":16,"column":49},"end":{"line":16,"column":53}},{"start":{"line":16,"column":56},"end":{"line":16,"column":61}}]}}};
}
__cov_p_$t2LNtAVB24eAC0nJR3A = __cov_p_$t2LNtAVB24eAC0nJR3A['c:\\Users\\vnaraujo\\projects\\stryker-mocha-chai-poc\\src\\module.js'];
__cov_p_$t2LNtAVB24eAC0nJR3A.s['1']++;var sum=(num1,num2)=>{__cov_p_$t2LNtAVB24eAC0nJR3A.s['2']++;return num1+num2;};__cov_p_$t2LNtAVB24eAC0nJR3A.s['3']++;var increment=number=>{__cov_p_$t2LNtAVB24eAC0nJR3A.s['4']++;return++number;};__cov_p_$t2LNtAVB24eAC0nJR3A.s['5']++;var decrement=number=>{__cov_p_$t2LNtAVB24eAC0nJR3A.s['6']++;return--number;};__cov_p_$t2LNtAVB24eAC0nJR3A.s['7']++;var isNegativeNumber=number=>{__cov_p_$t2LNtAVB24eAC0nJR3A.s['8']++;return number===Number.NEGATIVE_INFINITY?(__cov_p_$t2LNtAVB24eAC0nJR3A.b['1'][0]++,true):(__cov_p_$t2LNtAVB24eAC0nJR3A.b['1'][1]++,false);};__cov_p_$t2LNtAVB24eAC0nJR3A.s['9']++;var myModule={sum:sum,increment:increment,decrement:decrement,isNegativeNumber:isNegativeNumber};__cov_p_$t2LNtAVB24eAC0nJR3A.s['10']++;module.exports=myModule;
